# Vectors

Arrays (vectors, matrices, etc.) in Julia have a dual function: 

1. They act as *containers* that store information;
2. They behave like mathematical vectors and matrices.

[1] Define two vectors `v` y `w` with three components each.

[2] Try doing vector space operations on the vectors (adding two vectors, multiplying a vector by a scalar).

[3] Try multiplying two vectors. Does this work? What could/should this mean? If you want *element-by-element* operations, add a `.` before the operator name, e.g.  "`.*`" (MATLAB style). What about division?

[4] Guess the names for dot and cross product. Since Julia tries, when possible, to allow Unicode for mathematical notation, these can also be written
as `\cdot<TAB>` and `\times<TAB>`. Try it.

[5] Many mathematical functions are defined to act component-wise on vectors. Try your favourite ones. 

In [1]:
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [2]:
b = [4 5 6]

1×3 Array{Int64,2}:
 4  5  6

In [3]:
a*b

3×3 Array{Int64,2}:
  4   5   6
  8  10  12
 12  15  18

In [4]:
b*a

1-element Array{Int64,1}:
 32

In [5]:
a * a

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [6]:
a .* a

3-element Array{Int64,1}:
 1
 4
 9

In [7]:
a .* b

3×3 Array{Int64,2}:
  4   5   6
  8  10  12
 12  15  18

In [8]:
b .* a

3×3 Array{Int64,2}:
  4   5   6
  8  10  12
 12  15  18

Explanation:
https://julialang.org/blog/2017/01/moredots

More generally, if you combine two arrays of different dimensions or shapes, any “singleton” (length 1) or missing dimension of one array is “broadcasted” across that dimension of the other array. For example, A .+ [1,2,3] adds [1,2,3] to each column of an 3×n matrix A. Another typical example is to combine a row vector (or a 1×n array) and a column vector to make a matrix (2d array).

Great! Let's try:

In [9]:
A = zeros((3,3))

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [10]:
B = A .+ b

3×3 Array{Float64,2}:
 4.0  5.0  6.0
 4.0  5.0  6.0
 4.0  5.0  6.0

In [11]:
mean(B,1)

1×3 Array{Float64,2}:
 4.0  5.0  6.0

In [12]:
mean(B,2)

3×1 Array{Float64,2}:
 5.0
 5.0
 5.0

In [13]:
B .- mean(B,2)

3×3 Array{Float64,2}:
 -1.0  0.0  1.0
 -1.0  0.0  1.0
 -1.0  0.0  1.0

In [14]:
C = A .+ a

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 2.0  2.0  2.0
 3.0  3.0  3.0

In [15]:
C .- mean(C,1)

3×3 Array{Float64,2}:
 -1.0  -1.0  -1.0
  0.0   0.0   0.0
  1.0   1.0   1.0

In [16]:
double(x::Number) = 2*x

double (generic function with 1 method)

In [17]:
double(2)

4

In [18]:
double(a)

LoadError: MethodError: no method matching double(::Array{Int64,1})
Closest candidates are:
  double(::Number) at In[16]:1

In [19]:
double.(a)

3-element Array{Int64,1}:
 2
 4
 6

In [20]:
addtwo(a::Number,b::Number) = a+b

addtwo (generic function with 1 method)

In [21]:
addtwo(1,2)

3

In [22]:
addtwo.(a,b)

3×3 Array{Int64,2}:
 5  6  7
 6  7  8
 7  8  9

In [25]:
a .+ b

3×3 Array{Int64,2}:
 5  6  7
 6  7  8
 7  8  9

Also for performance:

In [38]:
a = ones(1_000_000)'
b = fill(2, 1_000_000)'

1×1000000 RowVector{Int64,Array{Int64,1}}:
 2  2  2  2  2  2  2  2  2  2  2  2  2  …  2  2  2  2  2  2  2  2  2  2  2  2

In [6]:
using BenchmarkTools

In [39]:
@btime $a += $b

  8.688 ms (9 allocations: 22.89 MiB)


1×1000000 RowVector{Float64,Array{Float64,1}}:
 3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  …  3.0  3.0  3.0  3.0  3.0  3.0  3.0

In [40]:
@btime $a .+= $b

  2.353 ms (0 allocations: 0 bytes)


1×1000000 RowVector{Float64,Array{Float64,1}}:
 8267.0  8267.0  8267.0  8267.0  8267.0  …  8267.0  8267.0  8267.0  8267.0

In [41]:
a = ones(1_000_000)'
b = fill(2, 1_000_000)'
a .+= b

1×1000000 RowVector{Float64,Array{Float64,1}}:
 3.0  3.0  3.0  3.0  3.0  3.0  3.0  3.0  …  3.0  3.0  3.0  3.0  3.0  3.0  3.0

# Creating vectors

There are various utility functions for creating vectors:

[1] Experiment with `zeros`, `ones`

Concatenation is possible using `;` inside the `[...]`.

[2] Create a vector containing 1 to 10, 20 to 30, followed by 100, using concatenation.

# Array comprehensions

Julia provides a powerful *array comprehension*  syntax for constructing vectors (or, in general, arrays) from another sequence.
This provides a syntax similar to the mathematical definition of a set; for example, the set $S$ defined by

$$S := \{ x^2 : x \in \{1, \ldots, 10 \} \}$$

is the set of the squares of the numbers from 1 to 10. In Julia we can accomplish this as

    S = [x^2 for x in 1:10]

[1] Use an array comprehension to define a function `my_exp` that gives an approximation to the exponential function.

[2] How could we use this to calculate `my_sin` and `my_cos`?

# Constructing vectors: `map`, `filter`

Given a vector (or, in general, an iterable), another vector may be created by applying a given function to each element
Two useful higher-order functions in Julia are:
1. `map`:    apply a given function to each element of a given iterable
2. `filter`: return only those elements for which a given condition is satisfied.

[6] Experiment with `map`. 

[7] Check the relative performance of `map` and an array comprehension for the same function and vector.

`filter` is often used with an *anonymous function* -- a function created with no name, for the sole purpose of using it in the `filter`. The Julia syntax for a function is similar to the mathematical syntax $x \mapsto 3x^2$:

    filter(x -> x < 10,  v)
    
[8] What kind of object is `x -> x < 10`?  (You can assign this to a variable.) Check that anonymous functions may also be 
    
[8] Check the relative performance of `filter` and the following syntax that also selects those elements of the array satisfying the given condition:

    v[v .< 10]
    
[9] What does `v .< 10` by itself do?

[Note that higher-order functions and anonymous functions are commonly thought to be "slow" currently in Julia, and so should not be used in performance-critical parts of code.]

In [42]:
?map

search: map map! mapfoldr mapfoldl mapslices mapreduce mapreducedim pmap Mmap



```
map(f, c...) -> collection
```

Transform collection `c` by applying `f` to each element. For multiple collection arguments, apply `f` elementwise.

```jldoctest
julia> map(x -> x * 2, [1, 2, 3])
3-element Array{Int64,1}:
 2
 4
 6

julia> map(+, [1, 2, 3], [10, 20, 30])
3-element Array{Int64,1}:
 11
 22
 33
```

```
map(f, x::Nullable)
```

Return `f` applied to the value of `x` if it has one, as a `Nullable`. If `x` is null, then return a null value of type `Nullable{S}`. `S` is guaranteed to be either `Union{}` or a concrete type. Whichever of these is chosen is an implementation detail, but typically the choice that maximizes performance would be used. If `x` has a value, then the return type is guaranteed to be of type `Nullable{typeof(f(x))}`.


In [45]:
@btime map(x->x^2,a)

  5.067 ms (11 allocations: 15.26 MiB)


1×1000000 RowVector{Float64,Array{Float64,1}}:
 9.0  9.0  9.0  9.0  9.0  9.0  9.0  9.0  …  9.0  9.0  9.0  9.0  9.0  9.0  9.0

In [47]:
@btime [x^2 for x in a]

  2.513 ms (4 allocations: 7.63 MiB)


1×1000000 Array{Float64,2}:
 9.0  9.0  9.0  9.0  9.0  9.0  9.0  9.0  …  9.0  9.0  9.0  9.0  9.0  9.0  9.0

## Static Arrays
Regular arrays are not very efficient. Consider adding two numbers:

In [24]:
# tuple version
addtwotuples(a,b) = (a[1]+b[1], a[2] + b[2])

addtwotuples (generic function with 1 method)

In [27]:
addtwotuples((1.0,2.0), (3.0,4.0))

(4.0, 6.0)

In [28]:
@code_native addtwotuples((1.0,2.0), (3.0,4.0))

	.text
Filename: In[24]
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 2
	movsd	(%rsi), %xmm0           # xmm0 = mem[0],zero
	movsd	8(%rsi), %xmm1          # xmm1 = mem[0],zero
	addsd	(%rdx), %xmm0
	addsd	8(%rdx), %xmm1
	movsd	%xmm0, (%rdi)
	movsd	%xmm1, 8(%rdi)
	movq	%rdi, %rax
	popq	%rbp
	retq
	nopw	%cs:(%rax,%rax)


In [29]:
@btime addtwotuples((1.0,2.0), (3.0,4.0))

  1.764 ns (0 allocations: 0 bytes)


(4.0, 6.0)

Array version:

In [10]:
[1.0,2.0] + [3.0,4.0]

2-element Array{Float64,1}:
 4.0
 6.0

In [14]:
@btime [1.0,2.0] + [3.0,4.0]

  89.000 ns (3 allocations: 288 bytes)


2-element Array{Float64,1}:
 4.0
 6.0

In [15]:
@code_native [1.0,2.0] + [3.0,4.0]

	.text
Filename: arraymath.jl
	pushq	%rbp
	movq	%rsp, %rbp
	pushq	%r15
	pushq	%r14
	pushq	%r12
	pushq	%rbx
	subq	$64, %rsp
	movq	%rsi, %r15
	movq	%rdi, %r14
	movq	%fs:0, %r12
	addq	$-10888, %r12           # imm = 0xD578
	xorpd	%xmm0, %xmm0
	movupd	%xmm0, -80(%rbp)
	movq	$4, -96(%rbp)
	movq	(%r12), %rax
	movq	%rax, -88(%rbp)
	leaq	-96(%rbp), %rax
	movq	%rax, (%r12)
Source line: 64
	movq	24(%r14), %rax
Source line: 64
	movq	24(%r15), %rcx
	xorl	%ebx, %ebx
Source line: 37
	testq	%rax, %rax
	cmovsq	%rbx, %rax
	movq	%rax, -40(%rbp)
	testq	%rcx, %rcx
	cmovsq	%rbx, %rcx
	movq	%rcx, -48(%rbp)
	movabsq	$promote_shape, %rax
	leaq	-40(%rbp), %rdi
	leaq	-48(%rbp), %rsi
	callq	*%rax
Source line: 64
	movq	24(%r14), %rax
Source line: 64
	movq	24(%r15), %rcx
Source line: 63
	testq	%rax, %rax
	cmovsq	%rbx, %rax
	movq	%rax, -56(%rbp)
	testq	%rcx, %rcx
	cmovnsq	%rcx, %rbx
	movq	%rbx, -64(%rbp)
	movabsq	$_bcs1, %rax
	leaq	-56(%rbp), %rdi
	leaq	-64(%rbp), %rsi
	callq	*%rax
	movq	%rax, %rbx
Source line: 266

### StaticArrays to the rescue!

In [16]:
using StaticArrays

In [34]:
function bench()
    x = SVector(1.0, 2.0)
    y = [1.0, 2.0]
    z = (1.0,2.0)
    
    @btime $x + $x
    @btime $y + $y
    @btime addtwotuples($z,$z)
end

bench (generic function with 1 method)

In [35]:
bench()

  2.014 ns (0 allocations: 0 bytes)
  32.620 ns (1 allocation: 96 bytes)
  2.014 ns (0 allocations: 0 bytes)


(2.0, 4.0)

In [37]:
@btime $v1+$v2

  2.014 ns (0 allocations: 0 bytes)


2-element SVector{2,Float64}:
 4.0
 6.0

In [23]:
@code_native v1+v2

	.text
Filename: linalg.jl
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 23
	movsd	(%rsi), %xmm0           # xmm0 = mem[0],zero
	movsd	8(%rsi), %xmm1          # xmm1 = mem[0],zero
	addsd	(%rdx), %xmm0
	addsd	8(%rdx), %xmm1
Source line: 10
	movsd	%xmm0, (%rdi)
	movsd	%xmm1, 8(%rdi)
	movq	%rdi, %rax
	popq	%rbp
	retq
	nopw	%cs:(%rax,%rax)
